"""empty message

Revision ID: 572b02850b8f
Revises: 18ba875b78f4
Create Date: 2015-03-15 10:20:15.586328

"""

# revision identifiers, used by Alembic.
revision = '572b02850b8f'
down_revision = '18ba875b78f4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
